Update default.rb
currently when use rsc_ros we run into the error:

/usr/local/bin/ros.rb -t download -c aws -u xxxxxxxxx -p xxxxxxxxx -b kabam-rs-artifacts -f xlate2/xxxxxxxxxx.tgz -d /tmp/xlate2.tgz -r us-west-1, STDOUT:, STDERR:/var/lib/gems/1.9.1/gems/fog-profitbricks-2.0.1/lib/fog/profitbricks.rb:4:in `<top (required)>': undefined local variable or method `__dir__' for main:Object (NameError)

as the new fog-profitbricks use __dir__ instead of old __FILE__ which requires ruby version higher than 1.9.3